name: build
on:
  push:
jobs:
  build:
    strategy:
      matrix:
        include:
          - name: windows-11
    runs-on: windows-2022
    steps:
          artifacts: output/*/*
          token: ${{ secrets.GITHUB_TOKEN }}
